# Generated by Django 5.2.3 on 2025-07-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoEducativo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=25, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='contenido/imagenes/')),
                ('videos', models.URLField(blank=True, null=True)),
                ('video_local', models.FileField(blank=True, null=True, upload_to='contenido/videos/')),
            ],
            options={
                'db_table': 'contenido_educativo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntregaMaterialReciclado',
            fields=[
                ('id_entrega_material', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('condiciones_entrega', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entrega_material_reciclado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entregas',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('confirmada', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entregas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialAceptado',
            fields=[
                ('id_ma', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'material_aceptado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialReciclable',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'material_reciclable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('clave_publicacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'publicaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PuntosReciclaje',
            fields=[
                ('id_punto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('ubicacion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('horario_entrada', models.TimeField(blank=True, null=True)),
                ('horario_salida', models.TimeField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('extras', models.TextField(blank=True, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'puntos_reciclaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recicladoras',
            fields=[
                ('codigo_recicladora', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('calle', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_postal', models.IntegerField(blank=True, null=True)),
                ('colonia', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_int', models.IntegerField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=30, null=True)),
                ('numero_telefonico', models.CharField(blank=True, max_length=20, null=True)),
                ('aprobada', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recicladoras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recompensas',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recompensas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Retos',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'retos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMaterialReciclable',
            fields=[
                ('id_tmr', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=40, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tiempo_descomposicion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='clasificacion/')),
            ],
            options={
                'db_table': 'tipo_material_reciclable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('ap_paterno', models.CharField(blank=True, max_length=25, null=True)),
                ('ap_materno', models.CharField(blank=True, max_length=25, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('contrasena', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('total_recompensas', models.IntegerField(blank=True, null=True)),
                ('puntos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuariosRecompensas',
            fields=[
                ('pk', models.CompositePrimaryKey('id_usuario', 'id_recompensa', blank=True, editable=False, primary_key=True, serialize=False)),
                ('fecha_canjeo', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios_recompensas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuariosRetos',
            fields=[
                ('pk', models.CompositePrimaryKey('id_usuario', 'id_reto', blank=True, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios_retos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_establecimiento', models.CharField(max_length=100)),
                ('ubicacion', models.TextField()),
                ('horarios_atencion', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('materiales_aceptados', models.TextField()),
                ('aprobado', models.BooleanField(default=False)),
            ],
        ),
    ]
