# Generated by Django 5.2.3 on 2025-07-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaMaterialReciclado',
            fields=[
                ('id_entrega_material', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('condiciones_entrega', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entrega_material_reciclado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialReciclable',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'material_reciclable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('clave_publicacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'publicaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recicladoras',
            fields=[
                ('codigo_recicladora', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('calle', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_postal', models.IntegerField(blank=True, null=True)),
                ('colonia', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_int', models.IntegerField(blank=True, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=30, null=True)),
                ('numero_telefonico', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'recicladoras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoMaterialReciclable',
            fields=[
                ('id_tipomaterial', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=40, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tiempo_descomposicion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_material_reciclable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuariosRecompensas',
            fields=[
                ('pk', models.CompositePrimaryKey('id_usuario', 'id_recompensa', blank=True, editable=False, primary_key=True, serialize=False)),
                ('fecha_canjeo', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios_recompensas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuariosRetos',
            fields=[
                ('pk', models.CompositePrimaryKey('id_usuario', 'id_reto', blank=True, editable=False, primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios_retos',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DetalleEntrega',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Empresas',
        ),
        migrations.DeleteModel(
            name='MaterialesReciclables',
        ),
        migrations.DeleteModel(
            name='TipoResiduo',
        ),
    ]
