# Generated by Django 5.2.3 on 2025-07-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_entregamaterialreciclado_materialreciclable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_establecimiento', models.CharField(max_length=100)),
                ('ubicacion', models.TextField()),
                ('horarios_atencion', models.CharField(max_length=100)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('materiales_aceptados', models.TextField()),
                ('aprobado', models.BooleanField(default=False)),
            ],
        ),
    ]
