# Generated by Django 5.2.3 on 2025-07-21 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_solicitudregistro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenidoeducativo',
            options={},
        ),
    ]
