# Generated by Django 5.2.3 on 2025-07-21 06:04

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_contenidoeducativo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidoeducativo',
            name='imagen',
            field=models.ImageField(upload_to='contenido/', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contenidoeducativo',
            name='video_local',
            field=models.FileField(upload_to='contenido/videos/', blank=True, null=True),
        ),
    ]
