# Generated by Django 5.2.3 on 2025-07-21 06:11


from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_imagen_y_video'),  # Asegúrate que es la última migración aplicada
    ]

    operations = [
        migrations.AddField(
            model_name='contenidoeducativo',
            name='videos',
            field=models.URLField(blank=True, null=True),
        ),
    ]

