# Generated by Django 5.2.3 on 2025-07-24 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_videos_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenidoeducativo',
            old_name='id_publicacion',
            new_name='codigo',
        ),
        migrations.RemoveField(
            model_name='contenidoeducativo',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='contenidoeducativo',
            name='fecha',
        ),
        migrations.AddField(
            model_name='contenidoeducativo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contenidoeducativo',
            name='id_usuario_ce',
            field=models.ForeignKey(blank=True, db_column='id_usuario_ce', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuarios'),
        ),
        migrations.AlterField(
            model_name='contenidoeducativo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='contenido/imagenes/'),
        ),
        migrations.AlterField(
            model_name='contenidoeducativo',
            name='titulo',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
