# Generated by Django 5.2.3 on 2025-07-29 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_videos_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenidoeducativo',
            options={'managed': False},
        ),
    ]
