# Generated by Django 5.2.3 on 2025-07-26 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_id_publicacion_contenidoeducativo_codigo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenidoeducativo',
            options={'managed': False},
        ),
    ]
